module.exports = [
    'kargoBidAdapter',
    'dfpAdServerVideo',
    'schain',
    'sharethroughBidAdapter',
    'sharethroughAnalyticsAdapter',
    'appnexusBidAdapter',
    'magniteAnalyticsAdapter',
    'rubiconBidAdapter',
    'pubmaticBidAdapter',
    'pubmaticAnalyticsAdapter',
    'tripleliftBidAdapter',
    'ixBidAdapter',
    'medianetBidAdapter',
    'medianetAnalyticsAdapter',
    'userId',
    '33acrossIdSystem',
    'id5IdSystem',
    'sharedIdSystem',
    'unifiedIdSystem',
    'liveIntentIdSystem',
    'hadronAnalyticsAdapter',
    'hadronIdSystem',
    'hadronRtdProvider'
  ];
  